//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class companyDBEntities : DbContext
    {
        public companyDBEntities()
            : base("name=companyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<tasks> tasks { get; set; }
        public virtual DbSet<projects> projects { get; set; }

        public virtual ObjectResult<getemployee_Result> getemployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getemployee_Result>("getemployee");
        }

        public virtual ObjectResult<proc_employeefor_datagrid_Result> proc_employeefor_datagrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_employeefor_datagrid_Result>("proc_employeefor_datagrid");
        }
    
        public virtual int proc_deleteemp(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_deleteemp", idParameter);
        }
    }
}
